float32: 'float'
float64: 'float'
int32: 'float'
int64: 'bigint'
bool: 'boolean'
datetime64[ns]: 'timestamp'
datetime64[ns, UTC]: 'timestamp'
datetime64[ns, EDT]: 'timestamp'
datetime64[ns, EST]: 'timestamp'
timedelta[ns]: 'varchar(max)'
object: 'varchar(max)'
